# Main transient
[main.branch]
kind = "transient"
key = "b"

[main.log]
kind = "transient"
key = "l"

[main.fetch]
kind = "transient"
key = "f"

# git branch transient
[branch.quiet]
kind = "flag"
key = "-q"

[branch.branch_name]
kind = "argument"
key = "-n"

[branch.start_point]
kind = "argument"
key = "-s"

# git checkout [-q] <branch_name>
[branch.checkout]
kind = "command"
key = "b"
base = ["git", "checkout"]
parameters = [
       { name = "quiet", render = "-q", optional = true },
       { name = "branch_name", render = "{branch_name}" },
]

[branch.create]
kind = "command"
key = "c"
base = ["git", "checkout"]
parameters = [
       { name = "branch_name", render = "{branch_name}" },
       { name = "start_point", render = "{start_point}", optional = false },
]

# git log transient
[log.log]
kind = "command"
key = "l"
base = [
       "git", "log",
]

[fetch.fetch]
kind = "command"
key = "f"
base = [
       "git", "fetch"
]
